name: FancyPortals
description: FancyPortals using things
main: com.sniperzciinema.portals.FancyPortals
version: 0.0.1
author: SniperzCiinema(xXSniperzzXx_SD)
commands:
   FancyPortals:
      description: Portalsssssss
      aliases: [fp, portals, portal, fancyportal]
      
permissions:
   FancyPortals.*:
      default: op
      children:
         FancyPortals.Create: true
         FancyPortals.Use: true
   
   FancyPortals.Use:
      default: true